spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=malongdel83@gmail.com
spring.datasource.password=dkgsgzahrruvkcdb
spring.flyway.enabled=false

jwt.secret=aJ8kL2mN5pQ9rT3vW7xZ1yB4cD6eF0gH3hJ5iK8lM1nO4qP7sSt0uV3wX6yZ9aB2cD
jwt.expirationMs=86400000